Etel/Models/Etel.cs
using System.ComponentModel.DataAnnotations;

namespace Etel.Models
{
    public class Etel
    {
        [Key]
        public string Id { get; set; }
        [Required]
        string Nev { get; set; }
        [Required]
        int Tapertek { get; set; }
        
        [Required]
        string Kategoria { get; set; }
        [Required]
        int Ar { get; set; }
        public string? ContentType { get; set; }
        public byte[]? Data { get; set; }

        public Etel()
        {
            Id = Guid.NewGuid().ToString();
        }
    }
}

Etel/Models/EtelClass.cs
using System.ComponentModel.DataAnnotations;

namespace Etel.Models
{
    public enum EtelTipus
    {
        [Display(Name = "Reggeli")]
        Reggeli,
        [Display(Name = "Ebéd")]
        Ebed,
        [Display(Name = "Vacsora")]
        Vacsora
    }

    public class EtelClass
    {
        [Key]
        public string Id { get; set; }
        [Required]
        [MaxLength(50)]
        public string Nev { get; set; }
        [Required]
        [Range(10, 1000)]
        public int Tapertek { get; set; }
        
        [Required]
        public string Kategoria { get; set; }
        [Required]
        [Range(100, 700)]
        public int Ar { get; set; }
        public string? ContentType { get; set; }
        public byte[]? Data { get; set; }

        public EtelClass()
        {
            Id = Guid.NewGuid().ToString();
        }
    }
}

Etel/Controllers/EtelController.cs
using Etel.Data;
using Etel.Models;
using Microsoft.AspNetCore.Mvc;

namespace Etel.Controllers
{
    public class EtelController : Controller
    {
        IEtelRepository repository;

        public EtelController(IEtelRepository repository)
        {
            this.repository = repository;
        }

        [OutputCache(Duration = 5, VaryByParam = "none")]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(EtelClass model, IFormFile picturedata)
        {
            if (model == null || !ModelState.IsValid)
            {
                return View();
            }

            using (var stream = picturedata.OpenReadStream())
            {
                byte[] buffer = new byte[picturedata.Length];
                stream.Read(buffer, 0, (int)picturedata.Length);

                model.Data = buffer;
                model.ContentType = picturedata.ContentType;
            }

            this.repository.Create(model);
            return View(null);
        }

        [HttpGet]
        [OutputCache(Duration = 5, VaryByParam = "none")]
        public IActionResult List(string kategoria)
        {
            if (kategoria == null)
            {
                var cucc = this.repository.Read();
                return View(cucc);
            }

            var etelek = this.repository.Read().Where(e => e.Kategoria == kategoria);
            return View(etelek);
        }
        public IActionResult GetImage(string id)
        {
            var etel = repository.ReadFromId(id);
            if (etel.ContentType != null && etel.ContentType.Length > 3)
            {
                return new FileContentResult(etel.Data, etel.ContentType);
            }
            else
            {
                return BadRequest();
            }

        }
    }
}

Etel/Views/Etel/Index.cshtml
@using Etel.Models;
@model EtelClass

@section head {
    <title>Étel hozzáadás</title>
}

<h1>Új étel hozzáadása</h1>

<form action="/Etel/Index" method="post" enctype="multipart/form-data">
    @Html.LabelFor(t => t.Nev)
    @Html.EditorFor(t => t.Nev)
    @Html.ValidationMessageFor(t => t.Nev)
    <br />

    @Html.LabelFor(t => t.Tapertek)
    @Html.EditorFor(t => t.Tapertek)
    @Html.ValidationMessageFor(t => t.Tapertek)
    <br />

    @Html.LabelFor(t => t.Kategoria)
    @Html.DropDownListFor(t => t.Kategoria, Html.GetEnumSelectList(typeof(EtelTipus)))
    @Html.ValidationMessageFor(t => t.Kategoria)
    <br />

    @Html.LabelFor(t => t.Ar)
    @Html.EditorFor(t => t.Ar)
    @Html.ValidationMessageFor(t => t.Ar)
    <br />

    <label>Kép:</label>
    <input type="file" name="picturedata" required />
    <br />

    <input type="submit" value="Hozzáad" />
</form>

Etel/Views/Etel/List.cshtml
@using Etel.Models;
@model IEnumerable<EtelClass>

    <form action="/Etel/List" method="get">
    @Html.DropDownList("kategoria", Html.GetEnumSelectList<EtelTipus>(), "ÖSSZES")
        <input type="submit" value="Szűrés" />
    </form>


<table>
    <thead>
        <tr>
            <th>Kép</th>
            <th>Név</th>
            <th>Tápérték</th>
            <th>Kategória</th>
            <th>Ár</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var etel in Model)
        {
            @:<tr>
                @:<td><img height="100" src="@Url.Action("GetImage", "Etel", new {Id = etel.Id})"</td>
                @:<td>@etel.Nev</td>
                @:<td>@etel.Tapertek</td>
                @:<td>@((EtelTipus)int.Parse(etel.Kategoria))</td>
                @:<td>@etel.Ar</td>
            @:</tr>
        }
    </tbody>
</table>

Etel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    @RenderSection("head", false)
</head>
<body>
    <div>
        <nav>
            <a href="/Etel/Index">Hozzáad</a>
            <a href="/Etel/List">Listáz</a>
        </nav>
        @RenderBody()
    </div>
</body>
</html>